#!/usr/bin/env python3
from pathlib import Path
import argparse
import re
import sys


JAVA_PATTERNS = [
    ("Controller", re.compile(r"\b@Controller\b|\b@RestController\b")),
    ("Service", re.compile(r"\b@Service\b|interface\s+\w*Service\b|class\s+\w*Service\b")),
    ("Mapper", re.compile(r"\b@Mapper\b|interface\s+\w*Mapper\b")),
    ("Config", re.compile(r"\b@Configuration\b")),
    ("Job", re.compile(r"\b@Scheduled\b|class\s+\w*(Job|Task|Scheduler)\b")),
]
XML_MAPPER = re.compile(r"<mapper\s+namespace=", re.IGNORECASE)
MAX_FILES_PER_GROUP = 80


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a lightweight read-only Java project map.")
    parser.add_argument("target", nargs="?", default=".", help="Target project directory")
    parser.add_argument("--output", help="Output Markdown path; defaults to .ai-coding-java/project-map.md")
    return parser.parse_args()


def skip_dir(path: Path) -> bool:
    return path.name in {".git", ".idea", ".vscode", "target", "build", "node_modules", ".ai-coding-java"}


def iter_files(root: Path):
    for path in root.rglob("*"):
        if any(skip_dir(part) for part in path.parents) or skip_dir(path):
            continue
        if path.is_file() and path.suffix in {".java", ".xml", ".yml", ".yaml", ".properties"}:
            yield path


def classify(path: Path) -> set[str]:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return set()
    groups: set[str] = set()
    if path.suffix == ".java":
        for name, pattern in JAVA_PATTERNS:
            if pattern.search(text):
                groups.add(name)
    elif path.suffix == ".xml" and XML_MAPPER.search(text):
        groups.add("Mapper XML")
    elif path.name in {"application.yml", "application.yaml", "application.properties"} or path.name.startswith("application-"):
        groups.add("Application Config")
    return groups


def rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def render(root: Path, groups: dict[str, list[Path]]) -> str:
    lines = [
        "# ai-coding-java Project Map",
        "",
        f"Target: {root}",
        "",
        "This file is generated by a read-only scan. Review it before using it as stable project knowledge.",
        "",
        "## Summary",
        "",
    ]
    for name in sorted(groups):
        lines.append(f"- {name}: {len(groups[name])}")
    lines.append("")
    for name in sorted(groups):
        lines.append(f"## {name}")
        lines.append("")
        for path in groups[name][:MAX_FILES_PER_GROUP]:
            lines.append(f"- `{rel(path, root)}`")
        omitted = len(groups[name]) - MAX_FILES_PER_GROUP
        if omitted > 0:
            lines.append(f"- ... {omitted} more")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    root = Path(args.target).expanduser().resolve()
    if not root.is_dir():
        print(f"FAIL target directory does not exist: {root}", file=sys.stderr)
        return 1

    groups: dict[str, list[Path]] = {}
    for path in iter_files(root):
        for group in classify(path):
            groups.setdefault(group, []).append(path)

    output = Path(args.output).expanduser().resolve() if args.output else root / ".ai-coding-java" / "project-map.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(root, groups), encoding="utf-8")
    print(f"OK wrote project map {output}")
    print("Summary: " + ", ".join(f"{name}={len(paths)}" for name, paths in sorted(groups.items())) if groups else "Summary: no Java project signals found")
    return 0


if __name__ == "__main__":
    sys.exit(main())
